package dev.irof.kifuzo.utils

object AppStrings {
    const val APP_TITLE = "Kifuzo（棋譜蔵）"
    const val SELECT_FOLDER = "フォルダ選択"
    const val IMPORT_KIFU = "棋譜をインポート"
    const val PASTE_KIFU = "棋譜を貼り付け"
    const val SETTINGS = "設定"
    const val KIFU_TEXT = "棋譜テキスト"
    const val COPY_AND_CLOSE = "コピーして閉じる"
    const val CLOSE = "閉じる"
    const val CANCEL = "キャンセル"
    const val OVERWRITE_CONFIRM = "上書き確認"
    const val OVERWRITE_ACTION = "上書きする"
    const val NOTIFICATION = "通知"
    const val ERROR = "エラー"
    const val OK = "OK"
    const val COPY = "コピー"
    const val START_POSITION = "開始局面"
    const val MOVE_COUNT = "手数"
    const val FLIP_BOARD = "盤面反転"
    const val CONVERT_TO_KIFU = "KIFUに変換"
    const val START = "開始"
    const val END = "終局"
    const val CONTACT = "衝突"
    const val MOVE_LIST = "指し手一覧"
    const val MY_NAME_REGEX_LABEL = "自分の名前の判定用（正規表現）:"
    const val AUTO_FLIP_HINT = "※自分が後手の場合、自動的に盤面を反転します。"
    const val RAW_PREFS_LABEL = "保存されている詳細データ (Preferences):"
    const val FILENAME_TEMPLATE_LABEL = "ファイル名の命名規則テンプレート:"
    const val FILENAME_TEMPLATE_HINT = "利用可能: {YYYYMMDD}, {Sente}, {Gote}"
    const val SAVE_SETTINGS = "設定を保存"
    const val SAVE_KIFU = "棋譜を保存"
    const val FILENAME = "ファイル名"
    const val SAVE = "保存"
    const val RENAME = "リネーム"
    const val SELECT_KIFU_HINT = "kifuファイルを選択してください"
    const val SELECT_KIFU_ROOT = "棋譜フォルダを選択してください"
    const val DELETE = "削除"
    const val HIERARCHY = "階層"
    const val FLAT = "フラット"
    const val FILTER_RECENT = "最近"
    const val SORT_NAME = "名前順"
    const val SORT_DATE = "更新順"

    const val LABEL_SENTE = "先手："
    const val LABEL_GOTE = "後手："
    const val LABEL_EVENT = "棋戦："
    const val LABEL_START_TIME = "開始日時："
    const val EDIT_METADATA = "棋譜情報の編集"
    const val OPEN_IN_SHOGIHOME = "ShogiHomeで開く"
    const val NO_METADATA_HINT = "（棋譜情報なし）"

    const val LABEL_QUEST = "将棋クエスト"
    const val LABEL_WARS = "将棋ウォーズ"
    const val LABEL_FILL_TIMESTAMP = "ファイルの更新日時から入力"
}
